{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ltt",
    "module": "pose-sdk",
    "version": "1.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "pose-sdk-1.0.4.aar",
          "url": "pose-sdk-1.0.4.aar",
          "size": 2376035,
          "sha512": "1bfed4001629d74d1959d5b71e01b0b67e34f9dd19eb5329ab5fc9c2de2021922d6c7f36325978371296713e51d00ff7e952ed2947030b97cfca9899a693620d",
          "sha256": "ab29e80b513285ab5a117ee3b58a0c6e32a91353f849dd73db9106f98e501f87",
          "sha1": "99e8fbe382760db9b2e56784043f84e294fd8a52",
          "md5": "e48fa925a5969c96e3382b6b6c8db057"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.10.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.google.mlkit",
          "module": "pose-detection",
          "version": {
            "requires": "18.0.0-beta4"
          }
        },
        {
          "group": "com.google.mlkit",
          "module": "pose-detection-accurate",
          "version": {
            "requires": "18.0.0-beta4"
          }
        },
        {
          "group": "com.google.mlkit",
          "module": "face-detection",
          "version": {
            "requires": "16.1.5"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "pose-sdk-1.0.4.aar",
          "url": "pose-sdk-1.0.4.aar",
          "size": 2376035,
          "sha512": "1bfed4001629d74d1959d5b71e01b0b67e34f9dd19eb5329ab5fc9c2de2021922d6c7f36325978371296713e51d00ff7e952ed2947030b97cfca9899a693620d",
          "sha256": "ab29e80b513285ab5a117ee3b58a0c6e32a91353f849dd73db9106f98e501f87",
          "sha1": "99e8fbe382760db9b2e56784043f84e294fd8a52",
          "md5": "e48fa925a5969c96e3382b6b6c8db057"
        }
      ]
    }
  ]
}
