{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ltt",
    "module": "pose-sdk",
    "version": "1.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "pose-sdk-1.0.8.aar",
          "url": "pose-sdk-1.0.8.aar",
          "size": 2379897,
          "sha512": "cfed40f5ad0e1a3cb51a85915537e8d7cd85de4d2c62ad88aee1f1da773a8a8a1b33c99698c3c2fac0987a5d8aba680bbf893d51b4dcf2cb266bb44119af15d1",
          "sha256": "110cdbf04d32b8b6543d59d502b5ffeb5bda8f750a23d1d8522b21dce95abfbf",
          "sha1": "71ec44a7d23bed5af074bcd094f664197d52bcc0",
          "md5": "932910148e03cdef7d2b1344aff2c090"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.10.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.google.mlkit",
          "module": "pose-detection",
          "version": {
            "requires": "18.0.0-beta4"
          }
        },
        {
          "group": "com.google.mlkit",
          "module": "pose-detection-accurate",
          "version": {
            "requires": "18.0.0-beta4"
          }
        },
        {
          "group": "com.google.mlkit",
          "module": "face-detection",
          "version": {
            "requires": "16.1.5"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "pose-sdk-1.0.8.aar",
          "url": "pose-sdk-1.0.8.aar",
          "size": 2379897,
          "sha512": "cfed40f5ad0e1a3cb51a85915537e8d7cd85de4d2c62ad88aee1f1da773a8a8a1b33c99698c3c2fac0987a5d8aba680bbf893d51b4dcf2cb266bb44119af15d1",
          "sha256": "110cdbf04d32b8b6543d59d502b5ffeb5bda8f750a23d1d8522b21dce95abfbf",
          "sha1": "71ec44a7d23bed5af074bcd094f664197d52bcc0",
          "md5": "932910148e03cdef7d2b1344aff2c090"
        }
      ]
    }
  ]
}
