{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ltt",
    "module": "pose-sdk",
    "version": "1.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "pose-sdk-1.0.7.aar",
          "url": "pose-sdk-1.0.7.aar",
          "size": 2380394,
          "sha512": "f2491cfc7d3ad3151ca83f9c7ee77e40a7e7199e67ee991f703445bedcb29c0fe34625b286ec40f72315c711178f82d9b567bf8159675a469580c4db7fdcfe34",
          "sha256": "a80587150b7f2ca7bb01fd0500f29bdab7d6e71ee5eb1997dc82b3d55c32a1aa",
          "sha1": "930ef88b6d0566c6b8462d9bfc51c3510ff6ba5e",
          "md5": "2b58b321625697f01d1a7dc20b69b3ed"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.10.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.google.mlkit",
          "module": "pose-detection",
          "version": {
            "requires": "18.0.0-beta4"
          }
        },
        {
          "group": "com.google.mlkit",
          "module": "pose-detection-accurate",
          "version": {
            "requires": "18.0.0-beta4"
          }
        },
        {
          "group": "com.google.mlkit",
          "module": "face-detection",
          "version": {
            "requires": "16.1.5"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "pose-sdk-1.0.7.aar",
          "url": "pose-sdk-1.0.7.aar",
          "size": 2380394,
          "sha512": "f2491cfc7d3ad3151ca83f9c7ee77e40a7e7199e67ee991f703445bedcb29c0fe34625b286ec40f72315c711178f82d9b567bf8159675a469580c4db7fdcfe34",
          "sha256": "a80587150b7f2ca7bb01fd0500f29bdab7d6e71ee5eb1997dc82b3d55c32a1aa",
          "sha1": "930ef88b6d0566c6b8462d9bfc51c3510ff6ba5e",
          "md5": "2b58b321625697f01d1a7dc20b69b3ed"
        }
      ]
    }
  ]
}
